title: Jiajia Wu
logo: "/images/logo.jpg?raw=true"
description: >
  Northwestern University <br>
  PHD Candiate <br>
  Biomedical Engineering <br>
  <br><br>
  MSU
  Bachelor in Electrical Engineering, Biomedical Concentration <br>
  Honors College Member <br>
  Minor in Cognitive Science <br>

  <a href="https://www.linkedin.com/in/jiajia-wu-3a0715174/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
